spring:
  application:
    name: movies  # C'est ici que vous ajoutez le nom !

  mongodb:
    uri: mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}/?appName=Cluster0
    database: ${env.MONGO_DATABASE}

server:
  port: 8080

# Optionnel : logging
logging:
  level:
    org.springframework.data.mongodb.core: DEBUG